name: aiml_2025_final_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - langchain-community
  - markdown
  - markupsafe
  - matplotlib
  - nbclient
  - nbformat
  - pip
  - pre-commit
  - python-decouple
  - scikit-learn
  - tqdm
  - pip:
      - chromadb
      - duckduckgo-search
      - ibm-watsonx-ai
      - instructor
      - langchain
      - langchain-chroma
      - langchain-core
      - langchain-ibm
      - langchain-text-splitters
      - langgraph
      - litellm
      - pandas
      - requests
      - pyowm
      - streamlit
      - torch
      - transformers==4.31.0
      - sentence-transformers==2.2.2
      - huggingface_hub==0.16.4
      - evaluate
      - datasets